### ISSUE TITLE
Issue when trying to run the code

### ISSUE THREAD

**Issue by KaiChen1998** [ricsonc/grnn#1]
Hi! Thank you for your great job first. But when I try to run your source code after I have download the shapenet data and pretrained .tar file and extract it in the same repo with `main.py` and run
```python
python main.py grnn_shapenet_eval
```
It doesn't work. It seems like it has the trouble finding the pre-trained weight. So what do you think is a better solution?
```
Traceback (most recent call last):
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key main/2Dencoder/Conv/biases not found in checkpoint
         [[{{node save_1/RestoreV2}}]]
         [[{{node save_1/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key main/2Dencoder/Conv/biases not found in checkpoint
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]

Caused by op 'save_1/RestoreV2', defined at:
  File "main.py", line 66, in <module>
    operator.go(const.mode)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 69, in go
    self.setup()
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 56, in setup
    self.step = self.load() #*0
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 102, in load
    return self.model.load(self.sess, self.loadname)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py", line 140, in load
    saver = tf.train.Saver(weights)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key main/2Dencoder/Conv/biases not found in checkpoint
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 66, in <module>
    operator.go(const.mode)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 69, in go
    self.setup()
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 56, in setup
    self.step = self.load() #*0
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 102, in load
    return self.model.load(self.sess, self.loadname)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py", line 141, in load
    saver.restore(sess, loadpath)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key main/2Dencoder/Conv/biases not found in checkpoint
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]

Caused by op 'save_1/RestoreV2', defined at:
  File "main.py", line 66, in <module>
    operator.go(const.mode)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 69, in go
    self.setup()
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 56, in setup
    self.step = self.load() #*0
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/operators.py", line 102, in load
    return self.model.load(self.sess, self.loadname)
  File "/nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py", line 140, in load
    saver = tf.train.Saver(weights)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/l/vision/v6/kaichen/anaconda/envs/grnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key main/2Dencoder/Conv/biases not found in checkpoint
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]
         [[node save_1/RestoreV2 (defined at /nfs/blitzle/home/data2/vision6/kaichen/grnn/models.py:140) ]]


If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by KaiChen1998** [comment]
initial commit

**Comment by ricsonc** [comment]
can you confirm that you have these files named 
`checkpoint  X-0.data-00000-of-00001  X-0.index  X-0.meta` in 
`path_to_repo/ckpt/grnn_shapenet_trained/main_weights`?

can you also check that inside the file `path_to_repo/ckpt_cfg/grnn_shapenet_trained` you have the lines
```
0
main_weights : main : ckpt/grnn_shapenet_trained/main_weights
```

**Comment by KaiChen1998** [comment]
- Yes, that's what confuses me. When I use the code to train a model first and then use it to do evaluation, it works. However when I try to use pre-trained weight file, it shows this error.

- Yeah, they are all like what you say. In fact I just use everything I download from your dropbox link.

**Comment by KaiChen1998** [comment]
> can you confirm that you have these files named
> `checkpoint X-0.data-00000-of-00001 X-0.index X-0.meta` in
> `path_to_repo/ckpt/grnn_shapenet_trained/main_weights`?
> 
> can you also check that inside the file `path_to_repo/ckpt_cfg/grnn_shapenet_trained` you have the lines
> 
> ```
> 0
> main_weights : main : ckpt/grnn_shapenet_trained/main_weights
> ```

Yes, that's what confuses me. When I use the code to train a model first and then use it to do evaluation, it works. However when I try to use pre-trained weight file, it shows this error.

Yeah, they are all like what you say. In fact I just use everything I download from your dropbox link.

**Comment by ricsonc** [comment]
Hm, could you go into `constants.py`, line 611 and change

```OG('grnn_shapenet_eval', 'gqn3d_convlstm_big_eval', load_name='grnn_shapenet_train')```

to 

```OG('grnn_shapenet_eval', 'gqn3d_convlstm_big_eval', load_name='grnn_shapenet_trained')```

and see if that helps?

**Comment by KaiChen1998** [comment]
Yeah, I have changed that in the very first time actually 2333.

**Comment by ricsonc** [comment]
I suspect this problem was caused by some tensorflow variable scope name being inadvertently modified when we were cleaning up the code. I pushed a slightly older version of the code to the branch "v2", which should work with the checkpoints.
